src/Entity/Todo.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TodoRepository")
 * @ORM\Table("todos")
 */
class Todo
{
    public const INCOMPLETE = 1;
    public const COMPLETE = 2;

    private static $names = [
        self::INCOMPLETE => 'incomplete',
        self::COMPLETE => 'completed',
    ];

    /**
     * @var int
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $title;

    /**
     * @var string
     * @ORM\Column(type="smallint")
     */
    private $status;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime", name="created_at")
     */
    private $createdAt;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime", name="updated_at")
     */
    private $updatedAt;

    /**
     * @param int $id
     */
    public function __construct(string $title, \DateTime $now)
    {
        $this->title = $title;
        $this->status = self::INCOMPLETE;
        $this->createdAt = $now;
        $this->updatedAt = $now;
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getTitle(): string
    {
        return $this->title;
    }

    /**
     * @return string
     */
    public function getStatusName(): string
    {
        return self::$names[$this->status];
    }


    public function update(string $title): void
    {
        $this->title = $title;
        $this->updatedAt = new \DateTime();
    }

    public function done(): void
    {
        $this->status = self::COMPLETE;
        $this->updatedAt = new \DateTime();
    }

    public function isActive(): bool
    {
        return self::INCOMPLETE === $this->status;
    }

}

src/Form/TodoType.php
<?php

declare(strict_types=1);

namespace App\Form;

use App\Entity\Todo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class TodoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('title', TextType::class, [
            'label' => 'title',
        ]);

        $transform = function ($data) { return $data; };
        $reverseTransform = function ($data) {
            return new Todo($data['title'], new \DateTime());
        };
        $builder->addModelTransformer(new CallbackTransformer($transform, $reverseTransform));
    }
}

src/Controller/DefaultController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Form\TodoType;
use App\Service\TodoList;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController
{
    /**
     * @var FormFactoryInterface
     */
    private $formFactory;

    /**
     * @var TodoList
     */
    private $todoList;

    /**
     * @param FormFactoryInterface $formFactory
     * @param TodoList             $todoList
     */
    public function __construct(FormFactoryInterface $formFactory, TodoList $todoList)
    {
        $this->formFactory = $formFactory;
        $this->todoList = $todoList;
    }

    /**
     * @Route("/")
     * @Template
     */
    public function index()
    {
        $todoForm = $this->formFactory->create(TodoType::class);

        return [
            'todoForm' => $todoForm->createView(),
            'todos' => $this->todoList->run(),
        ];
    }
}

src/Controller/Todo/DoneController.php
<?php

declare(strict_types=1);

namespace App\Controller\Todo;

use App\Entity\Todo;
use App\Service\DoneTodo;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\RouterInterface;

/**
 * @ParamConverter("todo",class="App:Todo")
 * @Route("/todo/{id}/done/", requirements={"id":"\d+"}, name="app_todo_done")
 * @Security("todo.isActive()")
 */
class DoneController
{
    /**
     * @var DoneTodo
     */
    private $doneTodo;

    /**
     * @var RouterInterface
     */
    private $router;

    /**
     * @param DoneTodo        $doneTodo
     * @param RouterInterface $router
     */
    public function __construct(DoneTodo $doneTodo, RouterInterface $router)
    {
        $this->doneTodo = $doneTodo;
        $this->router = $router;
    }

    public function __invoke(Todo $todo, Request $request)
    {
        $this->doneTodo->run($todo);
        $request->getSession()->getFlashBag()->add('success', 'Updated done, id #'.$todo->getId());

        return new RedirectResponse($this->router->generate('app_default_index'));
    }
}

src/Controller/Todo/NewController.php
<?php

declare(strict_types=1);

namespace App\Controller\Todo;

use App\Entity\Todo;
use App\Form\TodoType;
use App\Service\AddTodo;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;
use Symfony\Component\Routing\RouterInterface;

/**
 * Class NewController.
 *
 * @Route("/todo/new/",name="app_todo_new")
 * @Method("post")
 */
class NewController
{
    /**
     * @var FormFactoryInterface
     */
    private $formFactory;

    /**
     * @var AddTodo
     */
    private $addTodo;

    /**
     * @var RouterInterface
     */
    private $router;

    /**
     * @param FormFactoryInterface $formFactory
     * @param AddTodo              $addTodo
     * @param RouterInterface      $router
     */
    public function __construct(FormFactoryInterface $formFactory, AddTodo $addTodo, RouterInterface $router)
    {
        $this->formFactory = $formFactory;
        $this->addTodo = $addTodo;
        $this->router = $router;
    }

    /**
     * @param Request $request
     *
     * @return RedirectResponse
     *
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function __invoke(Request $request)
    {
        /** @var FlashBagInterface $flashBag */
        $flashBag = $request->getSession()->getFlashBag();
        $route = $this->router->generate('app_default_index');

        $form = $this->formFactory->create(TodoType::class);
        $form->handleRequest($request);

        if (false === $form->isValid()) {
            $flashBag->add('danger', 'Invalid form data');

            return new RedirectResponse($route);
        }

        /** @var Todo $todo */
        $todo = $form->getData();
        $this->addTodo->run($todo);
        $flashBag->add('success', sprintf('Created Todo, id #%d', $todo->getId()));

        return new RedirectResponse($route);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}TODO sample for Symfony4{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
        {% endblock %}
    </head>
    <body>
        {% block body %}
            <div class="container">
                {% for label, messages in app.flashes %}
                    {% for message in messages %}
                    <div class="alert alert-{{ label }}">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        {{ message }}
                    </div>
                    {% endfor %}
                {% endfor %}

                {% block contents %}
                {% endblock %}
            </div>
        {% endblock %}
        {% block javascripts %}
            <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
        {% endblock %}
    </body>
</html>

templates/default/index.html.twig
{% extends 'base.html.twig' %}
{% block contents %}
    <h1>TodoList</h1>
    <div class="row">
        <div class="col-sm-8">
            <table class="table">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Status</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for todo in todos %}
                    <tr>
                        <td>{{ todo.id }}</td>
                        <td>{{ todo.title }}</td>
                        <td>{{ todo.statusName }}</td>
                        <td>
                            {% if todo.isActive() %}
                                <a href="{{ path("app_todo_done",{"id": todo.id}) }}" class="btn btn-danger">Done</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
        <div class="col-sm-4">
            <div class="card">
                <div class="card-header">
                    Create New Todo
                </div>
                <div class="card-block">
                    <form method="post" action="{{ path("app_todo_new") }}">
                    {{ form_widget(todoForm) }}
                        <div class=""><button class="btn btn-primary" type="submit">Send</button></div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}